### ISSUE TITLE
Missing decryption key The provided decryption key is invalid. Check the URL and try again.

### ISSUE THREAD

**Issue by kiss-peter** [qgustavor/direct-mega#11]
Hello! What should I do now? I replace mega.nz with dirceme.ga and I get this error:
Missing decryption key
The provided decryption key is invalid. 
Check the URL and try again.
Regards, Peter

**Comment by qgustavor** [comment]
You take a link like this https://mega.nz/#!MAsFwa4b!d8o1uz6SffMAATSQmERLIYITkyc-eTbKQ6xqI3IQSms and replace like this https://directme.ga/#!MAsFwa4b!d8o1uz6SffMAATSQmERLIYITkyc-eTbKQ6xqI3IQSms

Only shared file links and shared folder links work, other kind of links will not work: pages like "https://mega.nz/#fm/account", "https://mega.nz/#fm/SomeCode" aren't public and internal pages like "https://mega.nz/#blog" and "https://mega.nz/#about" don't need any kind of "direct link".

**Comment by kiss-peter** [comment]
It's still not working :/ I'm trying it with this link: https://mega.nz/#!kz4gARzR!7e5Nn5OHSdHnmHBQ4T-WbS1lcvTm-dR_E-iabxNhFBE
In the first try I got to this: Direct to Mega..., then Webpage not found, now I get missing decryption key again.
https://directme.ga/#!kz4gARzR!7e5Nn5OHSdHnmHBQ4T-WbS1lcvTm-dR_E-iabxNhFBE
This is the directed link.

**Comment by qgustavor** [comment]
The link you passed is working. Maybe cleaning your browser cache will fix the problem.

**Comment by kiss-peter** [comment]
Do I have to install it, or something before accessing the link?

**Comment by kiss-peter** [comment]
I tried it with mozilla, now it's better. I get to this:
"Life Is Strange COMPLETE PC game.zip" opened

This file is larger than 1GB: you may have problems with bandwidth limits.
And nothing happens :/

**Comment by qgustavor** [comment]
If the file is larger than 1GB you can reach the MEGA's bandwidth limit while downloading and the download will never finish. This website don't avoids any bandwidth limits and, for now, it don't provides any workarounds to this.

It works better in Chrome, not Firefox, check this recording: https://gfycat.com/LegitimateOddballGardensnake

What can be happened is that you already reached the bandwidth limit and the website isn't showing this error, so I need to fix this. But that's not important because unless MEGA disable their bandwidth limits you will never going to download this file here, as it's too large.

If you just want to download this file and you're trying to avoid bandwidth limits Direct MEGA will not help you: this website don't avoids those, it only provides a direct link (like the recording above shows).

**Comment by qgustavor** [comment]
If you're having issues with bandwidth then use this tool: https://cdn.rawgit.com/qgustavor/7597642041427f2b4e78f324e8f91b14/raw/

**Comment by qgustavor** [comment]
I'm closing this issue: if you have bandwidth problems you can use [megajs-cli](https://github.com/qgustavor/megajs-cli) (if you find it hard to install subscribe to [this issue](https://github.com/qgustavor/megajs-cli/issues/5)). I'm also working in [the file splitter](https://directme.ga/splitter), but for now seems it's bugged.
