### ISSUE TITLE
This seems to be broken..?

### ISSUE THREAD

**Issue by LOuroboros** [qgustavor/direct-mega#20]
I just found this repository and wanted to give it a shot, so I grabbed a download link, replaced https://mega.nz with https://directme.ga and the screen is always stuck in "Direct MEGA - Please Wait..."
The download never begins.
![firefox_2018-07-15_02-19-07](https://user-images.githubusercontent.com/4485172/42730814-7bbc2646-87d5-11e8-85bc-426766243031.png)

**Comment by qgustavor** [comment]
I can't test it now, but from my tests it don't work well in Firefox as it
don't support creating readable streams.

There's a check testing if the browser supports it, IIRC in main.js. Maybe
this test is bugged: some browsers, like Safari, support creating streams
but those can't be used to initiate downloads, so it needs to blacklist
using user-agent detection. Well, it's a new feature in browsers so bugs
like those happen sometimes.

Can you investigate this? Check if the feature test is passing and if so
check developer console to see what's breaking the service worker. If it's
possible to fix it without blacklisting Firefox would be great, otherwise
we can blacklist it. You can send a pull request if you find a solution.

**Comment by LOuroboros** [comment]
I wish I could, but I don't have a single clue about all this stuff, hahaha.. I'm just a guy browsing the internet.

Btw, I just checked directme.ga using Ungoogled Chromium and Google Chrome, and while the result that I got was different, it wasn't favorable either, sadly.
Instead of getting stuck in a never ending loading screen, the link just takes me to the download in MEGA.

What's even weirder is that I made a test file with notepad afterwards, uploaded it to my MEGA account, I tried to download it using directme.ga.. and the download worked correctly..?
Maybe the issue in this case is the file format..? The 1st file I was trying to download is a .7z compressed folder.

**Comment by qgustavor** [comment]
In Chrome it's working as expected: 7z files aren't supported because those here used to distribute malware. This website only support image, video and audio files. Of course, it's possible to distribute malware using image files, but it's harder as additional steps are required, like renaming files. By only allowing those kind of file I avoid getting this website into a blacklist (example: other website of mine got into McAfee SiteAdvisor blacklist because of this). Also, anyone is free to fork the source code and remove this check (just undo [this commit](https://github.com/qgustavor/direct-mega/commit/42dca81916effce9f3e808e8d224951dcdc56ad5)).

But in Firefox it's not working as expected. I will try to find a fix for it, either downloading it (I only have Firefox 52 ESR, not latest version), ~~or using some online cross browser testing tool~~ (I couldn't find any tool which supports Firefox 61).

**Comment by qgustavor** [comment]
I tested on Firefox 61.0.1 and 63.0 Nightly and on both the fallback version was used. Seems, from your screenshot, that [main.js](https://github.com/qgustavor/direct-mega/blob/f1c01f2ca488d568e8ae6ae5b7082b84814ecef3/dist/main.js) ran but [fallback.js](https://github.com/qgustavor/direct-mega/blob/f1c01f2ca488d568e8ae6ae5b7082b84814ecef3/src/fallback.js) didn't. Maybe it was a network issue? I will put an error handler on main.js.

**Comment by qgustavor** [comment]
Closed because #21
