### ISSUE TITLE
Share the code

### ISSUE THREAD

**Issue by jimmywarting** [qgustavor/direct-mega#3]
Is there any chance for me to have a look at the un-minified source code?

**Comment by qgustavor** [comment]
It's qgustavor/mega plus a file which handles the Service Worker functions (sw.js).
I will publish it soon. I will not publish the full code (with the build scripts) because it's quite messy.

**Comment by jimmywarting** [comment]
Most interested in the sw.js so 😉

**Comment by qgustavor** [comment]
I could create an master branch with full source code, but by now I will only put the sw.js with the other files: https://github.com/qgustavor/direct-mega/blob/gh-pages/sw.js

The only dependencies are [qgustavor/mega](https://github.com/qgustavor/mega) and [mime-types](https://www.npmjs.com/package/mime-types/), so it's simple to understand and build.

Please note: I lost the sw.js which don't implement !view, so the current sw.js implements !view. The bug with !view is because it got too complicated with the fallback method (I needed to compile mega.js with [render-media](https://www.npmjs.com/package/render-media) generating a huge file).

I will remove the !view links from the readme, as the current sw.min.js don't support those.

**Edit:** I also removed !view support from sw.js, now the only dependency from it is [qgustavor/mega](https://github.com/qgustavor/mega).

**Comment by jimmywarting** [comment]
Cool, thanks!
Could learn a thing or two from this 😉

Mostly the part where you do the install event and also set the Content-Length to say how big the file is.

May do something similar in [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js)

**Comment by jimmywarting** [comment]
btw, on [sw.js#L42](https://github.com/qgustavor/direct-mega/blob/gh-pages/sw.js#L42) are you able to get a cancle event if the user aborted the download? I never got one in my StreamSaver test...

**Comment by qgustavor** [comment]
No, it put it here because it was in the spec, but even in the latest Chrome Canary it don't works.

The `// Try to make an stream, if it fails the SW don't install` fails in Firefox, so there are tests for ReadableStream support in [main.js#L25](https://github.com/qgustavor/direct-mega/blob/3096688d03977a5d3e5aa2665c67064e392e2d36/main.js#L25).

**Edit:** by the way, sorry for any English mistake.

**Comment by jimmywarting** [comment]
> fails in Firefox

Good to know

**Comment by jimmywarting** [comment]
thought you would be interested in following up on this bug jimmywarting/StreamSaver.js#13
reported here: w3c/ServiceWorker#957 and here: https://bugs.chromium.org/p/chromium/issues/detail?id=638494)
